### ISSUE TITLE
Session and cookies

### ISSUE THREAD

**Issue by kuslahne** [MiguelMJ/Milua#7]
Thank you Miguel for created this framework. I need to know how to implement session and cookies for milua?

**Comment by MiguelMJ** [comment]
Hi, @kuslahne , thank you!

Right now Milua doesn't have an interface for cookies because it is very minimal.
However, you can use cookies as you would with other http tools: using headers. Have a look at [mozilla's docs on this subject](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies). I hope you find it useful...

Thanks again!

***

I will keep this issue open in case any user is willing to implement an interface for cookies in Milua, though.
